export const ROBOSOC_SPIDER_FLOOR_Y = -1.16;
export const ROBOSOC_SPIDER_FLOOR_CLEARANCE = 0.004;
export const ROBOSOC_SPIDER_MODEL_ROOT_Y = -0.735;
export const ROBOSOC_SPIDER_MODEL_SCALE = 4.25;
export const ROBOSOC_SPIDER_WRAPPER_SCALE = 0.86;
